import 'src/shared/theme/globals.scss';

import clsx from 'clsx';
import type { Metadata } from 'next';

import { AppProviders } from 'src/shared/providers';
import { iranSansXFont } from 'src/shared/theme';
import { LocaleService } from 'src/shared/utils';

export const metadata: Metadata = {
  title: 'Resume Builder',
  description: 'Generated by Blufie team',
};

export default async function RootLayout({ children }: LayoutProps) {
  return (
    <html
      dir={LocaleService.getLocaleDir()}
      lang={LocaleService.getLang()}
      className={clsx(iranSansXFont.className, iranSansXFont.variable)}
    >
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
