import 'src/shared/theme/globals.scss';

import clsx from 'clsx';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { AppProviders } from 'src/shared/providers';
import { iranSansXFont } from 'src/shared/theme';
import { getLocaleLang } from 'src/shared/utils/locale';

export const metadata: Metadata = {
  title: 'Resume Builder',
  description: 'Generated by Blufie team',
};

export default async function RootLayout({ children, params }: LayoutProps) {
  // console.log({ props });

  const messages = await getMessages();

  return (
    <html
      dir="rtl"
      lang={getLocaleLang(params.locale)}
      className={clsx(iranSansXFont.className, iranSansXFont.variable)}
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <AppProviders>{children}</AppProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
